/* Banglasangbad — GitHub News Renderer vFinal
   News is read from /news-data.json generated by GitHub Actions.
*/
(function(){
'use strict';
const DATA_URL='news-data.json?v='+Date.now();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=v=>{const s=String(v||'').trim();return /^(https?:|\/|\.)/i.test(s)?s:''};
const norm=v=>{const s=String(v??'').trim();return /^\d+\.0+$/.test(s)?s.split('.')[0]:s};
const chars=s=>Array.from(String(s||'').trim());
const previewLimit=700;
const preview=t=>{const a=chars(t);return a.length>previewLimit?a.slice(0,previewLimit).join('')+'…':a.join('')};
const remainder=t=>chars(t).length>previewLimit?chars(t).slice(previewLimit).join('').trim():'';
function imageHtml(url,title){const src=safeUrl(url);return src?`<div class="news-image-top"><img src="${esc(src)}" alt="${esc(title)}" loading="lazy"></div>`:''}
function card(news,selected){
 const id=norm(news.id), full=String(news.text||'').trim(), more=remainder(full), cls=selected?' news-anchor-highlight':'';
 return `<article class="vertical-news-block${cls}" id="news-${esc(id)}" data-news-id="${esc(id)}">
 ${imageHtml(news.image,news.title)}
 <div class="news-text-bottom"><span class="category-tag">${esc(news.category||'সংবাদ')}</span>
 <div class="breaking-news-date">${esc(news.date||'')}</div><h3>${esc(news.title)}</h3>
 <p class="home-summary">${esc(preview(full)||'এই সংবাদের বিস্তারিত তথ্য পাওয়া যায়নি।')}</p>
 ${more?`<div class="home-full-details" id="full-news-${esc(id)}" hidden><p>${esc(more)}</p></div><button type="button" class="home-more-btn" data-more-id="${esc(id)}" aria-expanded="false">আরও</button>`:''}
 ${more?`<a href="news/${encodeURIComponent(id)}.html" class="read-more-btn breaking-detail-btn">আরও পড়ুন</a>`:''}
 </div></article>`;
}
function bindMore(root){root.querySelectorAll('[data-more-id]').forEach(btn=>btn.addEventListener('click',function(){const id=norm(this.dataset.moreId);const d=document.getElementById('full-news-'+id);if(!d)return;const open=this.getAttribute('aria-expanded')==='true';d.hidden=open;this.setAttribute('aria-expanded',String(!open));this.textContent=open?'আরও':'কম দেখুন';}));}
function selectedId(){return norm(new URLSearchParams(location.search).get('id')||'');}
function scrollSelected(id){if(!id)return;setTimeout(()=>{const el=document.getElementById('news-'+id);if(el)el.scrollIntoView({behavior:'smooth',block:'start'});},120);}
function renderHome(list){
 const c=document.getElementById('news-container'); if(!c)return;
 const sid=selectedId(); const selected=list.find(n=>norm(n.id)===sid); const ordered=selected?[selected,...list.filter(n=>norm(n.id)!==sid)]:[...list].reverse();
 c.innerHTML=ordered.map((n,i)=>card(n,i===0&&!!sid)).join(''); bindMore(c);
 const latest=document.getElementById('latest-news-container'); if(latest){latest.innerHTML=[...list].reverse().map(n=>{const id=norm(n.id);return `<div class="latest-item"><a href="home.html?id=${encodeURIComponent(id)}">🔺 ${esc(n.title)}</a></div>`}).join('');}
 const breaking=document.querySelector('.breaking .ticker-track'); if(breaking)breaking.textContent=(selected||list[list.length-1]).title||'';
 if(sid)scrollSelected(sid);
}
function normalizeCategory(v){return String(v||'').trim().toLowerCase().replace(/\s+/g,'');}
const categoryMap={
 'national.html':['জাতীয়','জাতীয়','national'],
 'politics.html':['রাজনীতি','politics'],
 'international.html':['আন্তর্জাতিক','international'],
 'economy.html':['অর্থনীতি','economy'],
 'sports.html':['খেলাধুলা','ক্রীড়া','ক্রীড়া','sports'],
 'entertainment.html':['বিনোদন','entertainment'],
 'technology.html':['প্রযুক্তি','technology'],
 'more.html':null
};
function renderCategory(list){
 const file=(location.pathname.split('/').pop()||'').toLowerCase(); const box=document.getElementById('category-news-container'); if(!box)return;
 const allowed=categoryMap[file]; const filtered=allowed?list.filter(n=>allowed.includes(normalizeCategory(n.category))):list;
 const ordered=[...filtered].reverse();
 box.innerHTML=`<h2 class="category-live-title">সর্বশেষ সংবাদ</h2>`+(ordered.length?ordered.map(n=>card(n,false)).join(''):'<p class="category-empty">এই বিভাগে এখনো কোনো সংবাদ পাওয়া যায়নি।</p>'); bindMore(box);
}
function ensureCategoryBox(){
 const file=(location.pathname.split('/').pop()||'').toLowerCase(); if(!categoryMap.hasOwnProperty(file))return;
 if(document.getElementById('category-news-container'))return;
 const box=document.createElement('section'); box.id='category-news-container'; box.className='category-live-news';
 const main=document.querySelector('main'); if(main)main.appendChild(box); else document.body.appendChild(box);
}
function setStyles(){
 if(document.getElementById('github-news-final-css'))return; const s=document.createElement('style');s.id='github-news-final-css';s.textContent=`
.category-live-news{max-width:1100px;margin:24px auto;padding:0 14px}.category-live-title{font-size:26px;margin:0 0 16px;border-left:5px solid #d71920;padding-left:10px}.category-live-news .vertical-news-block{background:#fff;border-radius:10px;box-shadow:0 2px 12px rgba(0,0,0,.07);overflow:hidden;margin:0 0 20px}.category-live-news .news-image-top img{width:100%;max-height:520px;object-fit:cover;display:block}.category-live-news .news-text-bottom{padding:18px}.category-live-news h3{font-size:24px;line-height:1.45;margin:8px 0}.category-live-news .home-summary{font-size:17px;line-height:1.9}.category-live-news .breaking-news-date{color:#777;font-size:13px}.category-empty{text-align:center;padding:30px;background:#fff;border-radius:10px}.home-full-details{margin-top:10px}.home-more-btn,.read-more-btn{display:inline-block;margin:8px 8px 0 0;padding:9px 15px;border:0;border-radius:6px;background:#d71920;color:#fff;text-decoration:none;cursor:pointer;font-weight:700}.news-anchor-highlight{scroll-margin-top:18px;outline:3px solid rgba(215,25,32,.18)}
@media(max-width:700px){.category-live-news{padding:0 10px;margin:18px auto}.category-live-title{font-size:21px}.category-live-news .news-text-bottom{padding:14px}.category-live-news h3{font-size:20px}.category-live-news .home-summary{font-size:16px}.category-live-news .news-image-top img{max-height:300px}}
`;document.head.appendChild(s);
}
setStyles();ensureCategoryBox();
fetch(DATA_URL,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json()}).then(data=>{const list=Array.isArray(data)?data:(Array.isArray(data.articles)?data.articles:[]);if(!list.length)throw Error('No news');if(document.getElementById('news-container'))renderHome(list);if(document.getElementById('category-news-container'))renderCategory(list);}).catch(err=>{console.error('GitHub news loading failed:',err);const c=document.getElementById('news-container');if(c)c.innerHTML='<div style="text-align:center;padding:40px;color:#888">খবর এই মুহূর্তে লোড করা যাচ্ছে না।</div>';});
})();
