/* বাংলা সংবাদ — GitHub-only news reader
   News data is generated by GitHub Actions into news-data.json.
   No Google Sheet is accessed by the website at runtime. */
(function(){
  const DATA_URL='news-data.json';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function imageUrl(url){
    const raw=String(url||'').trim();
    if(!raw) return '';
    return raw;
  }
  function ensureImages(){
    fetch(DATA_URL,{cache:'no-store'}).then(r=>r.ok?r.json():[]).then(list=>{
      const map=new Map((Array.isArray(list)?list:[]).map(n=>[String(n.id),n]));
      document.querySelectorAll('[data-news-id]').forEach(el=>{
        const id=el.getAttribute('data-news-id');
        const n=map.get(String(id));
        if(!n || !n.image) return;
        const card=el.closest('.news-card,.vertical-news-block,.news-item');
        if(!card) return;
        const img=card.querySelector('.news-image img,.news-image-top img,.news-image-wrap img,.news-primary-image img');
        if(img && !img.getAttribute('src')) img.src=imageUrl(n.image);
      });
    }).catch(()=>{});
  }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',ensureImages,{once:true});
  else ensureImages();
})();
